[package]
name = "halo2-snark-aggregator-api"
version = "0.1.0"
edition = "2021"
authors = ["zhangjunyu <junyu92@gmail.com>"]

[dependencies]
blake2b_simd = "1"
chrono = "0.4.19"
group = "0.11"
halo2_proofs = { git = "https://github.com/appliedzkp/halo2" }
pairing_bn256 = { git = "https://github.com/appliedzkp/pairing", tag = "v0.1.1" }
rand = "0.8"
rand_pcg = "0.3.1"
rand_xorshift = "0.3"
poseidon = { git = "https://github.com/appliedzkp/poseidon.git", branch = "circuit" }

[features]
default = ["halo2"]
blake2b = []
halo2 = []
plonk = []
